
public class CalculatorGUI extends javax.swing.JFrame {

    double first;
    double second;
    String operator;
    //is 1 when after equal we press a new number
    int equal_flag;
    //is 1 when we enter 1st digit of second number
    int second_flag;
    //is >=2 when we press operator second time instead of equal
    int operator_flag;
    //is >=2 when we choose to change operator after entering the first number
    int changeop_flag;
    //is 1 when we enter a new number after operations like sqr, sqrroot, %, etc
    int first_flag;
    //is 1 when we enter decimal point 
    int decimal_flag;
    
    public CalculatorGUI() {
        first = second = Double.NaN;
        operator = "";
        second_flag = 0;
        equal_flag = 0;
        changeop_flag = 0;
        operator_flag = 0;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(5, 0));

        jPanel1.setBackground(new java.awt.Color(221, 225, 225));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(221, 225, 225));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(221, 225, 225));
        jTextField3.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jTextField3.setForeground(java.awt.Color.gray);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setToolTipText("");
        jTextField3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setText("%");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton1.setBorderPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(27, 27));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton2.setText("√");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton3.setText(" x² ");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton4.setText("1/x");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jButton5.setText("← ");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jButton6.setText("÷");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton7.setText("CE");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton8.setText("C");
        jButton8.setToolTipText("");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton9.setText("9");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton9.setBorderPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jButton10.setText("×");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton10.setBorderPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton11.setText("6");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton11.setBorderPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(204, 204, 204));
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton12.setText("−");
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton12.setBorderPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton13.setText("4");
        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton13.setBorderPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(204, 204, 204));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton14.setText("5");
        jButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton14.setBorderPainted(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(204, 204, 204));
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton15.setText("7");
        jButton15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton15.setBorderPainted(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(204, 204, 204));
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton16.setText("8");
        jButton16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton16.setBorderPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(204, 204, 204));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton17.setText("1");
        jButton17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton17.setBorderPainted(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(204, 204, 204));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton18.setText("2");
        jButton18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton18.setBorderPainted(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(204, 204, 204));
        jButton19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton19.setText("3");
        jButton19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton19.setBorderPainted(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(204, 204, 204));
        jButton20.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton20.setText("+");
        jButton20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton20.setBorderPainted(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(204, 204, 204));
        jButton21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton21.setText(".");
        jButton21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton21.setBorderPainted(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(204, 204, 204));
        jButton22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton22.setText("=");
        jButton22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton22.setBorderPainted(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(204, 204, 204));
        jButton23.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton23.setText("±");
        jButton23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton23.setBorderPainted(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(204, 204, 204));
        jButton24.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton24.setText("0");
        jButton24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 242, 242)));
        jButton24.setBorderPainted(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//1/x
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String num = jTextField1.getText();
        first = Double.parseDouble(num);
        double temp = first;
        first = 1/first;
        if((first+"").length() > 18){
            first = Math.round(first * 1000000000000000D) / 1000000000000000D;
        }
        if ((first % 1) == 0)
            jTextField1.setText("" + (int)first);
        else
            jTextField1.setText("" + first);
        if((temp % 1) == 0)
            jTextField3.setText("1/(" + (int)temp + ") = ");
        else
            jTextField3.setText("1/(" + temp + ") = ");
        first_flag = 1;
        decimal_flag = 0;
    }//GEN-LAST:event_jButton4ActionPerformed
//sqr
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String num = jTextField1.getText();
        first = Double.parseDouble(num);
        double temp = first;
        first *= first;
        if((first+"").length() > 18){
            first = Math.round(first * 1000000000000000D) / 1000000000000000D;
        }
        if ((first % 1) == 0){
            jTextField1.setText("" + (int)first);
            jTextField3.setText("sqr(" + (int)temp + ") = ");
        }
        else{
            jTextField1.setText("" + first);
            jTextField3.setText("sqr(" + temp + ") = ");
        }
        first_flag = 1;
        decimal_flag = 0;
    }//GEN-LAST:event_jButton3ActionPerformed
//√
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String num = jTextField1.getText();
        first = Double.parseDouble(num);
        double temp = first;
        first = Math.sqrt(first);
        if((first+"").length() > 18){
            first = Math.round(first * 1000000000000000D) / 1000000000000000D;
        }
        if ((first % 1) == 0)
            jTextField1.setText("" + (int)first);
        else
            jTextField1.setText("" + first);
        if((temp % 1) == 0)
            jTextField3.setText("√(" + (int)temp + ") = ");
        else
            jTextField3.setText("√(" + temp + ") = ");
        first_flag = 1;
        decimal_flag = 0;
    }//GEN-LAST:event_jButton2ActionPerformed
//%
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String num = jTextField1.getText();
        first = Double.parseDouble(num);
        double temp = first;
        first = first/100;
        if((first+"").length() > 18){
            first = Math.round(first * 1000000000000000D) / 1000000000000000D;
        }
        if ((first % 1) == 0)
            jTextField1.setText("" + (int)first);
        else
            jTextField1.setText("" + first);
        if((temp % 1) == 0)
            jTextField3.setText((int)temp + "% = ");
        else
            jTextField3.setText(temp + "% = ");
        first_flag = 1;
        decimal_flag = 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed
//backspace
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String num = jTextField1.getText();
        if(jTextField3.getText().contains("=")){
            jTextField3.setText("");
            second_flag = 0;
            equal_flag = 0;
            operator_flag = 0;
            changeop_flag = 0;
            first_flag = 0;
            first = second = Double.NaN;
            operator = "";
            decimal_flag = 0;
        }
        else if(num != ""){
            char last = num.charAt(num.length()-1);
            if(num.length() == 1){
                if(operator.length() == 0)
                    first_flag = 1;
                else
                    second_flag = 1;
                num = "0";
            }
            else
                num = num.substring(0, num.length()-1);
            if(last == '.'){
                decimal_flag = 0;
            }

            jTextField1.setText(num);  
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed
//÷
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        decimal_flag = 0;
        String num = jTextField1.getText();
        operator_flag += 1;
        changeop_flag += 1;
        if(operator_flag >= 2 && changeop_flag <= 1){
            
            second = Double.parseDouble(num);
            
            if(operator.equals("×"))
            {
                first = first*second;
            }
            else if(operator.equals("÷"))
            {
                first = first/second;
            }
            else if(operator.equals("-"))
            {
                first = first-second;
            }
            else if(operator.equals("+"))
            {
                first = first+second;
            }
            if((first+"").length() > 18){
                first = Math.round(first * 1000000000000000D) / 1000000000000000D;
            }
            if ((first % 1) == 0){
                jTextField1.setText("" + (int)first);
                jTextField3.setText((int)first + " ÷ ");
            }
            else{
                jTextField1.setText("" + first);
                jTextField3.setText(first + " ÷ ");
            }
            operator = "÷";
            second_flag = 1;
        }
        else if(changeop_flag >= 2){
            operator = "÷";
            
            if ((first % 1) == 0){
                jTextField3.setText((int)first + " ÷ ");
            }
            else{
                jTextField3.setText(first + " ÷ ");
            }
        }
        else{
            equal_flag = 0;
            second_flag = 1;
            
            operator = "÷";
            
            first = Double.parseDouble(num);

            jTextField3.setText(num + " " + operator + " ");        
        }
    }//GEN-LAST:event_jButton6ActionPerformed
//CE
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        decimal_flag = 0;
        if(jTextField3.getText().contains("=") || operator.length() == 0){
            jTextField3.setText("");
            jTextField1.setText("0");
            second_flag = 0;
            equal_flag = 0;
            operator_flag = 0;
            changeop_flag = 0;
            first_flag = 0;
            first = second = Double.NaN;
            operator = "";
            decimal_flag = 0;
        }
        else if(operator.length() > 0){
            jTextField1.setText("0");
            second_flag = 1;
            decimal_flag = 0;
        }
    }//GEN-LAST:event_jButton7ActionPerformed
//C
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jTextField3.setText("");
        jTextField1.setText("0");
        second_flag = 0;
        equal_flag = 0;
        operator_flag = 0;
        changeop_flag = 0;
        first_flag = 0;
        first = second = Double.NaN;
        operator = "";
        decimal_flag = 0;
    }//GEN-LAST:event_jButton8ActionPerformed
//9
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        changeop_flag = 0;
        String num;
        if(first_flag == 1){
            first_flag = 0;
            jTextField1.setText("9");
            jTextField3.setText("");
            return;
        }
        if(operator.length() > 0){           
            if(second_flag == 1 || equal_flag == 1){
                second = Double.parseDouble("9");
                second_flag = 0;
                equal_flag = 0;  
            }
            else{
                String str;
                if(decimal_flag == 1){
                    str = (int)second + ".9";
                    decimal_flag = 2;
                }
                else if(decimal_flag == 2)
                    str = second + "9";
                else
                    str = (int)second + "9";
                
                second = Double.parseDouble(str);
            }
            if ((second % 1) == 0)
                jTextField1.setText("" + (int)second);
            else
                jTextField1.setText("" + second);
        }
        else{
            
            num = jTextField1.getText();
            if(num.equals("0")){
                num = "";
            }
            
            jTextField1.setText(num + "9");
        }
    }//GEN-LAST:event_jButton9ActionPerformed
//×
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        decimal_flag = 0;
        String num = jTextField1.getText();
        operator_flag += 1;
        changeop_flag += 1;
        if(operator_flag >= 2 && changeop_flag <= 1){
            
            second = Double.parseDouble(num);
            
            if(operator.equals("×"))
            {
                first = first*second;
            }
            else if(operator.equals("÷"))
            {
                first = first/second;
            }
            else if(operator.equals("-"))
            {
                first = first-second;
            }
            else if(operator.equals("+"))
            {
                first = first+second;
            }
            if((first+"").length() > 18){
                first = Math.round(first * 1000000000000000D) / 1000000000000000D;
            }
            if ((first % 1) == 0){
                jTextField1.setText("" + (int)first);
                jTextField3.setText((int)first + " × ");
            }
            else{
                jTextField1.setText("" + first);
                jTextField3.setText(first + " × ");
            }
            operator = "×";
            second_flag = 1;
        }
        else if(changeop_flag >= 2){
            operator = "×";
            if ((first % 1) == 0){
                jTextField3.setText((int)first + " × ");
            }
            else{
                jTextField3.setText(first + " × ");
            }
        }
        else{
            equal_flag = 0;
            second_flag = 1;
            
            operator = "×";
            
            first = Double.parseDouble(num);

            jTextField3.setText(num + " " + operator + " ");        
        }
        
    }//GEN-LAST:event_jButton10ActionPerformed
//6
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        changeop_flag = 0;
        String num;
        if(first_flag == 1){
            first_flag = 0;
            jTextField1.setText("6");
            jTextField3.setText("");
            return;
        }
        if(operator.length() > 0){           
            if(second_flag == 1 || equal_flag == 1){
                second = Double.parseDouble("6");
                second_flag = 0;
                equal_flag = 0;  
            }
            else{
                String str;
                if(decimal_flag == 1){
                    str = (int)second + ".6";
                    decimal_flag = 2;
                }
                else if(decimal_flag == 2)
                    str = second + "6";
                else
                    str = (int)second + "6";
                
                second = Double.parseDouble(str);
            }
            if ((second % 1) == 0)
                jTextField1.setText("" + (int)second);
            else
                jTextField1.setText("" + second);
        }
        else{
            
            num = jTextField1.getText();
            if(num.equals("0")){
                num = "";
            }
            
            jTextField1.setText(num + "6");
        }
    }//GEN-LAST:event_jButton11ActionPerformed
//-
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        decimal_flag = 0;
        String num = jTextField1.getText();
        operator_flag += 1;
        changeop_flag += 1;
        if(operator_flag >= 2 && changeop_flag <= 1){
           
            second = Double.parseDouble(num);
            
            if(operator.equals("×"))
            {
                first = first*second;
            }
            else if(operator.equals("÷"))
            {
                first = first/second;
            }
            else if(operator.equals("-"))
            {
                first = first-second;
            }
            else if(operator.equals("+"))
            {
                first = first+second;
            }
            if((first+"").length() > 18){
                first = Math.round(first * 1000000000000000D) / 1000000000000000D;
            }
            if ((first % 1) == 0){
                jTextField1.setText("" + (int)first);
                jTextField3.setText((int)first + " - ");
            }
            else{
                jTextField1.setText("" + first);
                jTextField3.setText(first + " - ");
            }
            operator = "-";
            second_flag = 1;
            
        }
        else if(changeop_flag >= 2){
            operator = "-";
            if ((first % 1) == 0){
                jTextField3.setText((int)first + " - ");
            }
            else{
                jTextField3.setText(first + " - ");
            }
        }
        else{
            equal_flag = 0;
            second_flag = 1;
            
            operator = "-";
            
            first = Double.parseDouble(num);

            jTextField3.setText(num + " " + operator + " ");        
        }
    }//GEN-LAST:event_jButton12ActionPerformed
//4
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        changeop_flag = 0;
        String num;
        if(first_flag == 1){
            first_flag = 0;
            jTextField1.setText("4");
            jTextField3.setText("");
            return;
        }
        if(operator.length() > 0){           
            if(second_flag == 1 || equal_flag == 1){
                second = Double.parseDouble("4");
                second_flag = 0;
                equal_flag = 0;  
            }
            else{
                String str;
                if(decimal_flag == 1){
                    str = (int)second + ".4";
                    decimal_flag = 2;
                }
                else if(decimal_flag == 2)
                    str = second + "4";
                else
                    str = (int)second + "4";
                
                second = Double.parseDouble(str);
            }
            if ((second % 1) == 0)
                jTextField1.setText("" + (int)second);
            else
                jTextField1.setText("" + second);
        }
        else{
            
            num = jTextField1.getText();
            if(num.equals("0")){
                num = "";
            }
            
            jTextField1.setText(num + "4");
        }
    }//GEN-LAST:event_jButton13ActionPerformed
//5
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        changeop_flag = 0;
        String num;
        if(first_flag == 1){
            first_flag = 0;
            jTextField1.setText("5");
            jTextField3.setText("");
            return;
        }
        if(operator.length() > 0){           
            if(second_flag == 1 || equal_flag == 1){
                second = Double.parseDouble("5");
                second_flag = 0;
                equal_flag = 0;  
            }
            else{
                String str;
                if(decimal_flag == 1){
                    str = (int)second + ".5";
                    decimal_flag = 2;
                }
                else if(decimal_flag == 2)
                    str = second + "5";
                else
                    str = (int)second + "5";
                
                second = Double.parseDouble(str);
            }
            if ((second % 1) == 0)
                jTextField1.setText("" + (int)second);
            else
                jTextField1.setText("" + second);
        }
        else{
            
            num = jTextField1.getText();
            if(num.equals("0")){
                num = "";
            }
            
            jTextField1.setText(num + "5");
        }

    }//GEN-LAST:event_jButton14ActionPerformed
//7
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        changeop_flag = 0;
        String num;
        if(first_flag == 1){
            first_flag = 0;
            jTextField1.setText("7");
            jTextField3.setText("");
            return;
        }
        if(operator.length() > 0){           
            if(second_flag == 1 || equal_flag == 1){
                second = Double.parseDouble("7");
                second_flag = 0;
                equal_flag = 0;  
            }
            else{
                String str;
                if(decimal_flag == 1){
                    str = (int)second + ".7";
                    decimal_flag = 2;
                }
                else if(decimal_flag == 2)
                    str = second + "7";
                else
                    str = (int)second + "7";
                
                second = Double.parseDouble(str);
            }
            if ((second % 1) == 0)
                jTextField1.setText("" + (int)second);
            else
                jTextField1.setText("" + second);
        }
        else{
            
            num = jTextField1.getText();
            if(num.equals("0")){
                num = "";
            }
            
            jTextField1.setText(num + "7");
        }
    }//GEN-LAST:event_jButton15ActionPerformed
//8
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        changeop_flag = 0;
        String num;
        if(first_flag == 1){
            first_flag = 0;
            jTextField1.setText("8");
            jTextField3.setText("");
            return;
        }
        if(operator.length() > 0){           
            if(second_flag == 1 || equal_flag == 1){
                second = Double.parseDouble("8");
                second_flag = 0;
                equal_flag = 0;  
            }
            else{
                String str;
                if(decimal_flag == 1){
                    str = (int)second + ".8";
                    decimal_flag = 2;
                }
                else if(decimal_flag == 2)
                    str = second + "8";
                else
                    str = (int)second + "8";
                
                second = Double.parseDouble(str);
            }
            if ((second % 1) == 0)
                jTextField1.setText("" + (int)second);
            else
                jTextField1.setText("" + second);
        }
        else{
            
            num = jTextField1.getText();
            if(num.equals("0")){
                num = "";
            }
            
            jTextField1.setText(num + "8");
        }
    }//GEN-LAST:event_jButton16ActionPerformed
//1
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        changeop_flag = 0;
        String num;
        if(first_flag == 1){
            first_flag = 0;
            jTextField1.setText("1");
            jTextField3.setText("");
            return;
        }
        if(operator.length() > 0){           
            if(second_flag == 1 || equal_flag == 1){
                second = Double.parseDouble("1");
                second_flag = 0;
                equal_flag = 0;  
            }
            else{
                String str;
                if(decimal_flag == 1){
                    str = (int)second + ".1";
                    decimal_flag = 2;
                }
                else if(decimal_flag == 2)
                    str = second + "1";
                else
                    str = (int)second + "1";
                
                second = Double.parseDouble(str);
            }
            if ((second % 1) == 0)
                jTextField1.setText("" + (int)second);
            else
                jTextField1.setText("" + second);
        }
        else{
            
            num = jTextField1.getText();
            if(num.equals("0")){
                num = "";
            }
            
            jTextField1.setText(num + "1");
        }
        
    }//GEN-LAST:event_jButton17ActionPerformed
//2
    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        String num;
        changeop_flag = 0;
        if(first_flag == 1){
            first_flag = 0;
            jTextField1.setText("2");
            jTextField3.setText("");
            return;
        }
        if(operator.length() > 0){
            
            if(second_flag == 1 || equal_flag == 1){
                second = Double.parseDouble("2");
                second_flag = 0;
                equal_flag = 0;
            }
            else{
                String str;
                if(decimal_flag == 1){
                    str = (int)second + ".2";
                    decimal_flag = 2;
                }
                else if(decimal_flag == 2)
                    str = second + "2";
                else
                    str = (int)second + "2";
                second = Double.parseDouble(str);
            }
            if ((second % 1) == 0)
                jTextField1.setText("" + (int)second);
            else
                jTextField1.setText("" + second);
        }
        else{
            num = jTextField1.getText();
            if(num.equals("0")){
                num = "";
            }
            jTextField1.setText(num + "2");
        }
    }//GEN-LAST:event_jButton18ActionPerformed
//3
    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        String num;
        changeop_flag = 0;
        if(first_flag == 1){
            first_flag = 0;
            jTextField1.setText("3");
            jTextField3.setText("");
            return;
        }
        if(operator.length() > 0){
            
            if(second_flag == 1 || equal_flag == 1){
                second = Double.parseDouble("3");
                second_flag = 0;
                equal_flag = 0;
                
            }
            else{
                String str;
                if(decimal_flag == 1){
                    str = (int)second + ".3";
                    decimal_flag = 2;
                }
                else if(decimal_flag == 2)
                    str = second + "3";
                else
                    str = (int)second + "3";
                second = Double.parseDouble(str);
            }
            if ((second % 1) == 0)
                jTextField1.setText("" + (int)second);
            else
                jTextField1.setText("" + second);
        }
        else{
            num = jTextField1.getText();
            if(num.equals("0")){
                num = "";
            }
            jTextField1.setText(num + "3");
        }
    }//GEN-LAST:event_jButton19ActionPerformed
//+
    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        decimal_flag = 0;
        String num = jTextField1.getText();
        operator_flag += 1;
        changeop_flag += 1;
        if(operator_flag >= 2 && changeop_flag <= 1){
            
            second = Double.parseDouble(num);
            
            if(operator.equals("×"))
            {
                first = first*second;
            }
            else if(operator.equals("÷"))
            {
                first = first/second;
            }
            else if(operator.equals("-"))
            {
                first = first-second;
            }
            else if(operator.equals("+"))
            {
                first = first+second;
            }
            if((first+"").length() > 18){
                first = Math.round(first * 1000000000000000D) / 1000000000000000D;
            }
            if ((first % 1) == 0){
                jTextField1.setText("" + (int)first);
                jTextField3.setText((int)first + " + ");
            }
            else{
                jTextField1.setText("" + first);
                jTextField3.setText(first + " + ");
            }
            operator = "+";
            second_flag = 1;
        }
        else if(changeop_flag >= 2){
            operator = "+";
            if ((first % 1) == 0){
                jTextField3.setText((int)first + " + ");
            }
            else{
                jTextField3.setText(first + " + ");
            }
        }
        else{
            equal_flag = 0;
            second_flag = 1;
            
            operator = "+";
            
            first = Double.parseDouble(num);

            jTextField3.setText(num + " " + operator + " ");        
        }
    }//GEN-LAST:event_jButton20ActionPerformed
//.
    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        if(equal_flag == 1 || second_flag == 1){
            //clear everything
            jTextField3.setText("");
            second_flag = 0;
            equal_flag = 0;
            operator_flag = 0;
            changeop_flag = 0;
            first_flag = 0;
            first = second = Double.NaN;
            operator = "";
            decimal_flag = 0;
        
            jTextField1.setText(0 + ".");
        }
        else if(decimal_flag == 0){
            jTextField1.setText(jTextField1.getText() + ".");
            decimal_flag = 1;
        }
    }//GEN-LAST:event_jButton21ActionPerformed
//=
    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        operator_flag = 0;
        changeop_flag = 0;
        
        String num = jTextField1.getText();
        if(equal_flag == 1){
            if(operator.length() > 0){
                first = Double.parseDouble(num);
                //double result = Double.sum(first, second);
                if(operator.equals("×"))
                {
                    first = first*second;
                }
                else if(operator.equals("÷"))
                {
                    first = first/second;
                }
                else if(operator.equals("-"))
                {
                    first = first-second;
                }
                else if(operator.equals("+"))
                {
                    first = first+second;
                }
                if((first+"").length() > 18){
                    first = Math.round(first * 1000000000000000D) / 1000000000000000D;
                }
                if ((first % 1) == 0)
                    jTextField1.setText("" + (int)first);
                else
                    jTextField1.setText("" + first);

                if ((second % 1) == 0 && (first % 1) == 0)
                    jTextField3.setText((int)first + " " + operator + " " + (int)second + " = ");

                else
                    jTextField3.setText(first + " " + second + " = ");
            }
            else{
                jTextField3.setText(num + " = ");
                first_flag = 1;
            }
        }
        else{
            equal_flag = 1;
            if(operator.length() == 0){
                jTextField3.setText(num + " = ");
                first_flag = 1;
            }
            else{
                second = Double.parseDouble(num);
                
                if(operator.equals("×"))
                {
                    first = first*second;
                }
                else if(operator.equals("÷"))
                {
                    first = first/second;
                }
                else if(operator.equals("-"))
                {
                    first = first-second;
                }
                else if(operator.equals("+"))
                {
                    first = first+second;
                }
                //result = Double.sum(first, second);
                if((first+"").length() > 18){
                    first = Math.round(first * 1000000000000000D) / 1000000000000000D;
                }
                if ((first % 1) == 0)
                    jTextField1.setText("" + (int)first);
                else
                    jTextField1.setText("" + first);

                if ((second % 1) == 0)
                    jTextField3.setText(jTextField3.getText() + " " + (int)second + " = ");

                else
                    jTextField3.setText(jTextField3.getText() + " " + second + " = ");

            }
        }
        
    }//GEN-LAST:event_jButton22ActionPerformed
//+-
    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        String num = jTextField1.getText();
        first = Double.parseDouble(num);
        if(first == 0)
            return;
        first = -1*first;
        if ((first % 1) == 0){
            jTextField1.setText("" + (int)first);
        }
        else
            jTextField1.setText("" + first);
        jTextField3.setText("");
        first_flag = 1;
        decimal_flag = 0;
        
    }//GEN-LAST:event_jButton23ActionPerformed
//0
    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        changeop_flag = 0;
        String num;
        if(first_flag == 1){
            first_flag = 0;
            jTextField1.setText("0");
            jTextField3.setText("");
            return;
        }
        if(operator.length() > 0){           
            if(second_flag == 1 || equal_flag == 1){
                second = Double.parseDouble("0");
                second_flag = 0;
                equal_flag = 0;  
            }
            else{
                String str;
                if(decimal_flag == 1){
                    str = (int)second + ".0";
                    decimal_flag = 2;
                }
                else if(decimal_flag == 2)
                    str = second + "0";
                else
                    str = (int)second + "0";
                
                second = Double.parseDouble(str);
            }
            if ((second % 1) == 0)
                jTextField1.setText("" + (int)second);
            else
                jTextField1.setText("" + second);
        }
        else{
            
            num = jTextField1.getText();
            if(num.equals("0")){
                num = "";
            }
            
            jTextField1.setText(num + "0");
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
